import { HomePageBlogsSection } from '@blog/presentation/components/blogs/organisms/HomePageBlogsSection';
import { HomePageGoodReadsSection } from '@blog/presentation/components/books/organisms/HomePageGoordReadsSection';
import { getRecentBlogsQuery } from '@blog/presentation/queries/blogs/get-recent-blogs';
import { dehydrate, QueryClient } from '@tanstack/react-query';
import { GetStaticProps } from 'next';
import Head from 'next/head';

export default function Home() {
    return (
        <>
            <Head>
                <title>Weijland.IT</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex flex-col items-stretch gap-40">
                <HomePageBlogsSection />
                <HomePageGoodReadsSection />
            </div>
        </>
    );
}

export const getStaticProps: GetStaticProps = async (context) => {
    const queryClient = new QueryClient();

    const query = getRecentBlogsQuery();

    await Promise.all([queryClient.prefetchQuery(...query)]);

    return {
        props: {
            dehydratedState: dehydrate(queryClient),
        },
    };
};
