import { HomePageBlogsSection } from 'blog/presentation/components/blogs/organisms/HomePageBlogsSection';
import { Footer } from 'blog/presentation/components/shared/organisms/Footer';
import { NavigationMenu } from 'blog/presentation/components/shared/organisms/NavigationMenu';
import Head from 'next/head';

export default function Home() {
    return (
        <>
            <Head>
                <title>Weijland.IT</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="py-8 max-w-5xl mx-auto w-full flex flex-col gap-36 items-stretch">
                <NavigationMenu />
                <HomePageBlogsSection />
                <Footer />
            </div>
        </>
    );
}
